language: go
go:
  - 1.9
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="icalF"
    - GIT_EMAIL="laser.survivor@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="source"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
before_install:
  - openssl aes-256-cbc -K $encrypted_a24742169c78_key -iv $encrypted_a24742169c78_iv -in $SSH_KEY.enc -out $SSH_KEY -d
install:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo
  - go install github.com/gohugoio/hugo
  - hugo version
  - npm version
  - npm install
script:
  - npm run build
  - ls $SOURCE_DIR -al
deploy:
  provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
