language: go
go:
  - 1.9.4

cache:
  directories:
    - $GOPATH/bin

install:
  - uname -a
  - cd $TRAVIS_BUILD_DIR
  - if [ ! -d "$GOPATH/bin/hugo" ]; then
      curl -L -O $HUGO_URL;
      tar xzf $ARCHIVE;
      chmod +x hugo;
      mv hugo $GOPATH/bin;
    fi
  - hugo version
  - npm version
  - npm install

before_script:
  - cp config.toml.$TRAVIS_BRANCH config.toml

script:
  - npm run build
  - ls public -Ral

deploy:

- provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
    
- provider: pages
  local_dir: public
  repo: koneko096/staging
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: staging
