language: go
go:
  - 1.9

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo
  - go install github.com/gohugoio/hugo
  - hugo version
  - npm version
  - npm install

script:
  - npm run build
  - ls public -al

deploy:

- provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
    
- provider: pages
  local_dir: public
  repo: icalF/staging
  target_branch: staging
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: staging
