language: go
go:
  - 1.11.1

cache:
  directories:
    - $GOPATH/src/github.com/magefile
    - $GOPATH/src/github.com/gohugoio
    - $GOPATH/pkg
    - $GOPATH/bin

install:
  - cd $HOME
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install --tags extended
  - cd $TRAVIS_BUILD_DIR;
  - hugo version
  - npm version
  - npm install

before_script:
  - cp config.toml.$TRAVIS_BRANCH config.toml

script:
  - npm run build
  - ls public -Ral

deploy:

- provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
    
- provider: pages
  local_dir: public
  repo: icalF/staging
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: staging
