language: go
go:
  - 1.9

cache:
  directories:
    - $GOPATH/src/github.com/kardianos
    - $GOPATH/src/github.com/gohugoio
    - $GOPATH/pkg

install:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo
  - go install github.com/gohugoio/hugo
  - hugo version
  - npm version
  - npm install

before_script:
  - cp config.toml.$TRAVIS_BRANCH config.toml

script:
  - npm run build
  - ls public -Ral

deploy:

- provider: pages
  local_dir: public
  target_branch: master
  keep-history: true
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
    
- provider: pages
  local_dir: public
  repo: icalF/staging
  target_branch: master
  keep-history: true
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: staging
