language: go
go:
  - 1.9

cache:
  directories:
    - $GOPATH/src/github.com/magefile
    - $GOPATH/src/github.com/gohugoio
    - $GOPATH/pkg
    - $GOPATH/bin

install:
  - go get github.com/magefile/mage
  - if [ -d "$GOPATH/src/github.com/gohugoio/hugo" ]; then
      go get -d github.com/gohugoio/hugo;
    fi
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - cd $TRAVIS_BUILD_DIR
  - hugo version
  - npm version
  - npm install

before_script:
  - cp config.toml.$TRAVIS_BRANCH config.toml

script:
  - npm run build
  - ls public -Ral

deploy:

- provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
    
- provider: pages
  local_dir: public
  repo: icalF/staging
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: staging
