contentdir: "content"
languageCode: "en-us"
layoutdir: "layouts"
publishdir: "public"
Paginate: 8
indexes:
  category: "categories"
baseurl: "http://icalF.github.io/blog"
title: "Hajimemashite"
canonifyurls: true
theme: "purehugo"
