baseurl = "https://icalF.github.io"
languageCode = "en-us"
title = "Postmortem"
enableEmoji = true
copyright = "&copy; <a href=\"https://github.com/icalF\">Afrizal Fikri</a> 2017"
newContentEditor = "vim"
hasCJKLanguage = true
theme = "hemingway"
pygmentsStyle = "native"
draft = false
Paginate = 8

[permalinks]
  report = "/report/:year/:month/:day/:title"

[params]
  disqusShortname = "postmortem-1"
  googleAnalytics = "UA-111769411-1"
  
[params.highlight]
style = "github"
languages = ["go", "java", "javascript"]

[[params.social]]
url = "https://github.com/icalF"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/ical_fikr"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
