baseurl = "https://icalF.github.io/blog"
languageCode = "en-us"
title = "Hajimemashite"
enableEmoji = true
newContentEditor = "vim"
theme = "purehugo"
pygmentsStyle = "native"
draft = false
Paginate = 8

[params]
  twitterName = "ical_fikr"
  githubName = "icalF"
  description = "Yoroshiku onegaishimasu"
  hideShareOptions = true
