baseurl = "https://icalF.github.io"
languageCode = "en-us"
title = "Postmortem"
enableEmoji = true
copyright = "&copy; <a href=\"https://github.com/icalF\">Afrizal Fikri</a> 2017"
newContentEditor = "vim"
hasCJKLanguage = true
theme = "hemingway"
pygmentsStyle = "native"
draft = false
Paginate = 8
disqusShortname = "postmortem-1"


[permalinks]
  report = "/report/:year/:month/:day/:title"
  
[params.highlight]
style = "github"
languages = ["go", "java", "javascript", "bash", "elixir"]

[[params.social]]
url = "https://facebook.com/icalFikr"
fa_icon = "fa-facebook"

[[params.social]]
url = "https://t.me/icalFikr"
fa_icon = "fa-telegram"

[[params.social]]
url = "https://github.com/icalF"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/ical_fikr"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
